<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\Continent;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $af = Continent::where('code', 'AF')->firstOrFail();
        $as = Continent::where('code', 'AS')->firstOrFail();
        $eu = Continent::where('code', 'EU')->firstOrFail();
        $na = Continent::where('code', 'NA')->firstOrFail();
        $sa = Continent::where('code', 'SA')->firstOrFail();
        $oc = Continent::where('code', 'OC')->firstOrFail();

        $countries = [
            // ── AFRICA (alphabetical) ─────────────────────────────────────────
            [$af->id, 'Algeria',                    'DZA', '+213'],
            [$af->id, 'Angola',                     'AGO', '+244'],
            [$af->id, 'Benin',                      'BEN', '+229'],
            [$af->id, 'Botswana',                   'BWA', '+267'],
            [$af->id, 'Burkina Faso',               'BFA', '+226'],
            [$af->id, 'Burundi',                    'BDI', '+257'],
            [$af->id, 'Cabo Verde',                 'CPV', '+238'],
            [$af->id, 'Cameroon',                   'CMR', '+237'],
            [$af->id, 'Central African Republic',   'CAF', '+236'],
            [$af->id, 'Chad',                       'TCD', '+235'],
            [$af->id, 'Comoros',                    'COM', '+269'],
            [$af->id, 'Congo',                      'COG', '+242'],
            [$af->id, "Côte d'Ivoire",              'CIV', '+225'],
            [$af->id, 'Djibouti',                   'DJI', '+253'],
            [$af->id, 'DR Congo',                   'COD', '+243'],
            [$af->id, 'Egypt',                      'EGY', '+20'],
            [$af->id, 'Equatorial Guinea',          'GNQ', '+240'],
            [$af->id, 'Eritrea',                    'ERI', '+291'],
            [$af->id, 'Eswatini',                   'SWZ', '+268'],
            [$af->id, 'Ethiopia',                   'ETH', '+251'],
            [$af->id, 'Gabon',                      'GAB', '+241'],
            [$af->id, 'Gambia',                     'GMB', '+220'],
            [$af->id, 'Ghana',                      'GHA', '+233'],
            [$af->id, 'Guinea',                     'GIN', '+224'],
            [$af->id, 'Guinea-Bissau',              'GNB', '+245'],
            [$af->id, 'Kenya',                      'KEN', '+254'],
            [$af->id, 'Lesotho',                    'LSO', '+266'],
            [$af->id, 'Liberia',                    'LBR', '+231'],
            [$af->id, 'Libya',                      'LBY', '+218'],
            [$af->id, 'Madagascar',                 'MDG', '+261'],
            [$af->id, 'Malawi',                     'MWI', '+265'],
            [$af->id, 'Mali',                       'MLI', '+223'],
            [$af->id, 'Mauritania',                 'MRT', '+222'],
            [$af->id, 'Mauritius',                  'MUS', '+230'],
            [$af->id, 'Morocco',                    'MAR', '+212'],
            [$af->id, 'Mozambique',                 'MOZ', '+258'],
            [$af->id, 'Namibia',                    'NAM', '+264'],
            [$af->id, 'Niger',                      'NER', '+227'],
            [$af->id, 'Nigeria',                    'NGA', '+234'],
            [$af->id, 'Rwanda',                     'RWA', '+250'],
            [$af->id, 'São Tomé and Príncipe',      'STP', '+239'],
            [$af->id, 'Senegal',                    'SEN', '+221'],
            [$af->id, 'Seychelles',                 'SYC', '+248'],
            [$af->id, 'Sierra Leone',               'SLE', '+232'],
            [$af->id, 'Somalia',                    'SOM', '+252'],
            [$af->id, 'South Africa',               'ZAF', '+27'],
            [$af->id, 'South Sudan',                'SSD', '+211'],
            [$af->id, 'Sudan',                      'SDN', '+249'],
            [$af->id, 'Tanzania',                   'TZA', '+255'],
            [$af->id, 'Togo',                       'TGO', '+228'],
            [$af->id, 'Tunisia',                    'TUN', '+216'],
            [$af->id, 'Uganda',                     'UGA', '+256'],
            [$af->id, 'Zambia',                     'ZMB', '+260'],
            [$af->id, 'Zimbabwe',                   'ZWE', '+263'],

            // ── ASIA (alphabetical) ───────────────────────────────────────────
            [$as->id, 'Afghanistan',                'AFG', '+93'],
            [$as->id, 'Armenia',                    'ARM', '+374'],
            [$as->id, 'Azerbaijan',                 'AZE', '+994'],
            [$as->id, 'Bahrain',                    'BHR', '+973'],
            [$as->id, 'Bangladesh',                 'BGD', '+880'],
            [$as->id, 'Bhutan',                     'BTN', '+975'],
            [$as->id, 'Brunei',                     'BRN', '+673'],
            [$as->id, 'Cambodia',                   'KHM', '+855'],
            [$as->id, 'China',                      'CHN', '+86'],
            [$as->id, 'Cyprus',                     'CYP', '+357'],
            [$as->id, 'Georgia',                    'GEO', '+995'],
            [$as->id, 'India',                      'IND', '+91'],
            [$as->id, 'Indonesia',                  'IDN', '+62'],
            [$as->id, 'Iran',                       'IRN', '+98'],
            [$as->id, 'Iraq',                       'IRQ', '+964'],
            [$as->id, 'Israel',                     'ISR', '+972'],
            [$as->id, 'Japan',                      'JPN', '+81'],
            [$as->id, 'Jordan',                     'JOR', '+962'],
            [$as->id, 'Kazakhstan',                 'KAZ', '+7'],
            [$as->id, 'Kuwait',                     'KWT', '+965'],
            [$as->id, 'Kyrgyzstan',                 'KGZ', '+996'],
            [$as->id, 'Laos',                       'LAO', '+856'],
            [$as->id, 'Lebanon',                    'LBN', '+961'],
            [$as->id, 'Malaysia',                   'MYS', '+60'],
            [$as->id, 'Maldives',                   'MDV', '+960'],
            [$as->id, 'Mongolia',                   'MNG', '+976'],
            [$as->id, 'Myanmar',                    'MMR', '+95'],
            [$as->id, 'Nepal',                      'NPL', '+977'],
            [$as->id, 'North Korea',                'PRK', '+850'],
            [$as->id, 'Oman',                       'OMN', '+968'],
            [$as->id, 'Pakistan',                   'PAK', '+92'],
            [$as->id, 'Palestine',                  'PSE', '+970'],
            [$as->id, 'Philippines',                'PHL', '+63'],
            [$as->id, 'Qatar',                      'QAT', '+974'],
            [$as->id, 'Russia',                     'RUS', '+7'],
            [$as->id, 'Saudi Arabia',               'SAU', '+966'],
            [$as->id, 'Singapore',                  'SGP', '+65'],
            [$as->id, 'South Korea',                'KOR', '+82'],
            [$as->id, 'Sri Lanka',                  'LKA', '+94'],
            [$as->id, 'Syria',                      'SYR', '+963'],
            [$as->id, 'Taiwan',                     'TWN', '+886'],
            [$as->id, 'Tajikistan',                 'TJK', '+992'],
            [$as->id, 'Thailand',                   'THA', '+66'],
            [$as->id, 'Timor-Leste',                'TLS', '+670'],
            [$as->id, 'Turkey',                     'TUR', '+90'],
            [$as->id, 'Turkmenistan',               'TKM', '+993'],
            [$as->id, 'United Arab Emirates',       'ARE', '+971'],
            [$as->id, 'Uzbekistan',                 'UZB', '+998'],
            [$as->id, 'Vietnam',                    'VNM', '+84'],
            [$as->id, 'Yemen',                      'YEM', '+967'],

            // ── EUROPE (alphabetical) ─────────────────────────────────────────
            [$eu->id, 'Albania',                    'ALB', '+355'],
            [$eu->id, 'Andorra',                    'AND', '+376'],
            [$eu->id, 'Austria',                    'AUT', '+43'],
            [$eu->id, 'Belarus',                    'BLR', '+375'],
            [$eu->id, 'Belgium',                    'BEL', '+32'],
            [$eu->id, 'Bosnia and Herzegovina',     'BIH', '+387'],
            [$eu->id, 'Bulgaria',                   'BGR', '+359'],
            [$eu->id, 'Croatia',                    'HRV', '+385'],
            [$eu->id, 'Czechia',                    'CZE', '+420'],
            [$eu->id, 'Denmark',                    'DNK', '+45'],
            [$eu->id, 'Estonia',                    'EST', '+372'],
            [$eu->id, 'Finland',                    'FIN', '+358'],
            [$eu->id, 'France',                     'FRA', '+33'],
            [$eu->id, 'Germany',                    'DEU', '+49'],
            [$eu->id, 'Greece',                     'GRC', '+30'],
            [$eu->id, 'Hungary',                    'HUN', '+36'],
            [$eu->id, 'Iceland',                    'ISL', '+354'],
            [$eu->id, 'Ireland',                    'IRL', '+353'],
            [$eu->id, 'Italy',                      'ITA', '+39'],
            [$eu->id, 'Latvia',                     'LVA', '+371'],
            [$eu->id, 'Liechtenstein',              'LIE', '+423'],
            [$eu->id, 'Lithuania',                  'LTU', '+370'],
            [$eu->id, 'Luxembourg',                 'LUX', '+352'],
            [$eu->id, 'Malta',                      'MLT', '+356'],
            [$eu->id, 'Moldova',                    'MDA', '+373'],
            [$eu->id, 'Monaco',                     'MCO', '+377'],
            [$eu->id, 'Montenegro',                 'MNE', '+382'],
            [$eu->id, 'Netherlands',                'NLD', '+31'],
            [$eu->id, 'North Macedonia',            'MKD', '+389'],
            [$eu->id, 'Norway',                     'NOR', '+47'],
            [$eu->id, 'Poland',                     'POL', '+48'],
            [$eu->id, 'Portugal',                   'PRT', '+351'],
            [$eu->id, 'Romania',                    'ROU', '+40'],
            [$eu->id, 'San Marino',                 'SMR', '+378'],
            [$eu->id, 'Serbia',                     'SRB', '+381'],
            [$eu->id, 'Slovakia',                   'SVK', '+421'],
            [$eu->id, 'Slovenia',                   'SVN', '+386'],
            [$eu->id, 'Spain',                      'ESP', '+34'],
            [$eu->id, 'Sweden',                     'SWE', '+46'],
            [$eu->id, 'Switzerland',                'CHE', '+41'],
            [$eu->id, 'Ukraine',                    'UKR', '+380'],
            [$eu->id, 'United Kingdom',             'GBR', '+44'],
            [$eu->id, 'Vatican City',               'VAT', '+379'],

            // ── NORTH AMERICA (alphabetical) ──────────────────────────────────
            [$na->id, 'Anguilla',                       'AIA', '+1-264'],
            [$na->id, 'Antigua and Barbuda',            'ATG', '+1-268'],
            [$na->id, 'Aruba',                          'ABW', '+297'],
            [$na->id, 'Bahamas',                        'BHS', '+1-242'],
            [$na->id, 'Barbados',                       'BRB', '+1-246'],
            [$na->id, 'Belize',                         'BLZ', '+501'],
            [$na->id, 'Bermuda',                        'BMU', '+1-441'],
            [$na->id, 'British Virgin Islands',         'VGB', '+1-284'],
            [$na->id, 'Canada',                         'CAN', '+1'],
            [$na->id, 'Costa Rica',                     'CRI', '+506'],
            [$na->id, 'Cuba',                           'CUB', '+53'],
            [$na->id, 'Curaçao',                        'CUW', '+599'],
            [$na->id, 'Dominica',                       'DMA', '+1-767'],
            [$na->id, 'Dominican Republic',             'DOM', '+1-809'],
            [$na->id, 'El Salvador',                    'SLV', '+503'],
            [$na->id, 'Grenada',                        'GRD', '+1-473'],
            [$na->id, 'Guatemala',                      'GTM', '+502'],
            [$na->id, 'Haiti',                          'HTI', '+509'],
            [$na->id, 'Honduras',                       'HND', '+504'],
            [$na->id, 'Jamaica',                        'JAM', '+1-876'],
            [$na->id, 'Mexico',                         'MEX', '+52'],
            [$na->id, 'Montserrat',                     'MSR', '+1-664'],
            [$na->id, 'Nicaragua',                      'NIC', '+505'],
            [$na->id, 'Panama',                         'PAN', '+507'],
            [$na->id, 'Puerto Rico',                    'PRI', '+1-787'],
            [$na->id, 'Saint Kitts and Nevis',          'KNA', '+1-869'],
            [$na->id, 'Saint Lucia',                    'LCA', '+1-758'],
            [$na->id, 'Saint Vincent and the Grenadines','VCT', '+1-784'],
            [$na->id, 'Sint Maarten',                   'SXM', '+1-721'],
            [$na->id, 'Trinidad and Tobago',            'TTO', '+1-868'],
            [$na->id, 'Turks and Caicos Islands',       'TCA', '+1-649'],
            [$na->id, 'United States',                  'USA', '+1'],
            [$na->id, 'United States Virgin Islands',   'VIR', '+1-340'],

            // ── SOUTH AMERICA (alphabetical) ──────────────────────────────────
            [$sa->id, 'Argentina',          'ARG', '+54'],
            [$sa->id, 'Bolivia',            'BOL', '+591'],
            [$sa->id, 'Brazil',             'BRA', '+55'],
            [$sa->id, 'Chile',              'CHL', '+56'],
            [$sa->id, 'Colombia',           'COL', '+57'],
            [$sa->id, 'Ecuador',            'ECU', '+593'],
            [$sa->id, 'Falkland Islands',   'FLK', '+500'],
            [$sa->id, 'French Guiana',      'GUF', '+594'],
            [$sa->id, 'Guyana',             'GUY', '+592'],
            [$sa->id, 'Paraguay',           'PRY', '+595'],
            [$sa->id, 'Peru',               'PER', '+51'],
            [$sa->id, 'Suriname',           'SUR', '+597'],
            [$sa->id, 'Uruguay',            'URY', '+598'],
            [$sa->id, 'Venezuela',          'VEN', '+58'],

            // ── OCEANIA (alphabetical) ─────────────────────────────────────────
            [$oc->id, 'Australia',          'AUS', '+61'],
            [$oc->id, 'Fiji',               'FJI', '+679'],
            [$oc->id, 'Kiribati',           'KIR', '+686'],
            [$oc->id, 'Marshall Islands',   'MHL', '+692'],
            [$oc->id, 'Micronesia',         'FSM', '+691'],
            [$oc->id, 'Nauru',              'NRU', '+674'],
            [$oc->id, 'New Zealand',        'NZL', '+64'],
            [$oc->id, 'Palau',              'PLW', '+680'],
            [$oc->id, 'Papua New Guinea',   'PNG', '+675'],
            [$oc->id, 'Samoa',              'WSM', '+685'],
            [$oc->id, 'Solomon Islands',    'SLB', '+677'],
            [$oc->id, 'Tonga',              'TON', '+676'],
            [$oc->id, 'Tuvalu',             'TUV', '+688'],
            [$oc->id, 'Vanuatu',            'VUT', '+678'],
        ];

        foreach ($countries as [$continentId, $name, $code, $dialCode]) {
            Country::updateOrCreate(
                ['code' => $code],
                ['continent_id' => $continentId, 'name' => $name, 'code' => $code, 'country_code' => $dialCode]
            );
        }

        $this->command->info('Countries seeded successfully! Total: ' . count($countries));
    }
}
